version: '3'
services:
  strings:
    build:
      dockerfile: StringsServiceDebugDockerfile
    hostname: strings_server
    security_opt:
      - "seccomp:unconfined"
    cap_add:
        - SYS_PTRACE    
    ports:
      - 50051:50051
      - 40001:40001
  numbers:
    build:
      dockerfile: NumbersServiceDebugDockerfile
    hostname: numbers_server
    security_opt:
      - "seccomp:unconfined"
    cap_add:
        - SYS_PTRACE    
    ports:
      - 50052:50052
      - 40002:40002
  api:
    build:
      dockerfile: ApiDebugDockerfile
    security_opt:
      - "seccomp:unconfined"
    cap_add:
        - SYS_PTRACE
    ports:
      - 8080:8080
      - 40000:40000
    depends_on:
      - strings
      - numbers