// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: number_service.proto

package numberspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumberServiceClient is the client API for NumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumberServiceClient interface {
	AddTwoNumbers(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResult, error)
	SubtractTwoNumbers(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResult, error)
}

type numberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNumberServiceClient(cc grpc.ClientConnInterface) NumberServiceClient {
	return &numberServiceClient{cc}
}

func (c *numberServiceClient) AddTwoNumbers(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, "/number_services.NumberService/AddTwoNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberServiceClient) SubtractTwoNumbers(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, "/number_services.NumberService/SubtractTwoNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumberServiceServer is the server API for NumberService service.
// All implementations must embed UnimplementedNumberServiceServer
// for forward compatibility
type NumberServiceServer interface {
	AddTwoNumbers(context.Context, *OperationRequest) (*OperationResult, error)
	SubtractTwoNumbers(context.Context, *OperationRequest) (*OperationResult, error)
	mustEmbedUnimplementedNumberServiceServer()
}

// UnimplementedNumberServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNumberServiceServer struct {
}

func (UnimplementedNumberServiceServer) AddTwoNumbers(context.Context, *OperationRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTwoNumbers not implemented")
}
func (UnimplementedNumberServiceServer) SubtractTwoNumbers(context.Context, *OperationRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubtractTwoNumbers not implemented")
}
func (UnimplementedNumberServiceServer) mustEmbedUnimplementedNumberServiceServer() {}

// UnsafeNumberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumberServiceServer will
// result in compilation errors.
type UnsafeNumberServiceServer interface {
	mustEmbedUnimplementedNumberServiceServer()
}

func RegisterNumberServiceServer(s grpc.ServiceRegistrar, srv NumberServiceServer) {
	s.RegisterService(&NumberService_ServiceDesc, srv)
}

func _NumberService_AddTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberServiceServer).AddTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/number_services.NumberService/AddTwoNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberServiceServer).AddTwoNumbers(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumberService_SubtractTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberServiceServer).SubtractTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/number_services.NumberService/SubtractTwoNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberServiceServer).SubtractTwoNumbers(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NumberService_ServiceDesc is the grpc.ServiceDesc for NumberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NumberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "number_services.NumberService",
	HandlerType: (*NumberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTwoNumbers",
			Handler:    _NumberService_AddTwoNumbers_Handler,
		},
		{
			MethodName: "SubtractTwoNumbers",
			Handler:    _NumberService_SubtractTwoNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "number_service.proto",
}
